@echo off
echo Creating fonts directory...
if not exist "storage\fonts" mkdir "storage\fonts"
echo Downloading DejaVu Sans font...
powershell -Command "& {Invoke-WebRequest -Uri 'https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip' -OutFile 'dejavu-fonts.zip'}"
echo Extracting font...
powershell -Command "& {Expand-Archive -Path 'dejavu-fonts.zip' -DestinationPath 'temp' -Force}"
echo Moving font to storage/fonts directory...
copy /y "temp\dejavu-fonts-ttf-2.37\ttf\DejaVuSans.ttf" "storage\fonts\"
echo Cleaning up...
rd /s /q temp
del dejavu-fonts.zip
echo Done!